name: Deploy to STAGING

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Standard permission for GitHub Actions

on:
  push:
    branches:
      - main
      - fix/msg-processing
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
      IMAGE_NAME: ${{ vars.PUBLICECR_URI }}
      IMAGE_TAG: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PUBLICECR_UPLOAD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PUBLICECR_UPLOAD_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.PUBLICECR_REGION }}

      - name: Authenticate with AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build a Docker image
        run: |
          make build

      - name: Publish To AWS ECR
        run: |
          docker push ${{ vars.PUBLICECR_URI }}:staging

      # TODO : uncomment once the redeploy role is created
      # - name: Authenticate with AWS ECS
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ vars.AWS_STAGING_ECS_REDEPLOY_ROLE_ARN }}
      #     aws-region: ${{ vars.AWS_STAGING_REGION }}

      # - name: Trigger new deployment
      #   run: |
      #     aws ecs update-service \
      #       --cluster ${{ vars.AWS_STAGING_ECS_CLUSTER }} \
      #       --service ${{ vars.AWS_STAGING_ECS_SERVICE }} \
      #       --force-new-deployment

      # - name: Wait until the service is stable
      #   run: |
      #     aws ecs wait services-stable \
      #       --cluster ${{ vars.AWS_STAGING_ECS_CLUSTER }} \
      #       --service ${{ vars.AWS_STAGING_ECS_SERVICE }}
